apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.10.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/clusters/prd/platform/external-secrets/values.yaml
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      path: clusters/prd/platform/external-secrets
      directory:
        include: resources.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
