apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lab-homelab
spec:
  blocks:
    - cidr: 192.168.5.21/32
  serviceSelector:
    matchLabels:
      lb-pool: lab-homelab
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lab-homelab
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enp
    - ^eth
  nodeSelector: {}
