apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/clusters/prd/platform/cert-manager/values.yaml
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      path: clusters/prd/platform/cert-manager
      directory:
        include: resources.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
