# Discover nested Applications under platform/ and apps/.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      path: clusters/prd/platform
      directory:
        recurse: true
        include: '*/application.yaml'
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      path: clusters/prd/apps
      directory:
        recurse: true
        include: '*/application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
