apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iscsi-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.15.1
      helm:
        releaseName: scarif-iscsi
        valueFiles:
          - $values/clusters/prd/platform/iscsi-csi/values.yaml
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      path: clusters/prd/platform/iscsi-csi
      directory:
        include: resources.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
