apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: https://1password.github.io/connect-helm-charts
      chart: connect
      targetRevision: 2.4.1
      helm:
        releaseName: onepassword-connect
        valueFiles:
          - $values/clusters/prd/platform/onepassword-connect/values.yaml
    - repoURL: https://github.com/jacobdrury/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
